spring:
  mail:
    host: email-smtp.us-west-2.amazonaws.com
    port: 587
    username: phxofc-dev-2023
    password: PpP4|(5'

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

server:
  port: 8081